### ISSUE TITLE
CARGO environment variable ignored

### ISSUE THREAD

**Issue by dmitrii-ubskii** [messense/cargo-options#8]
`cargo_command()` is hardcoded to be just `cargo` [1], which will fail if it is not in `PATH`. This becomes a problem for CI and hermetic builds. cargo-options should respect the environment variables specified by Cargo [2].

[1] https://github.com/messense/cargo-options/blob/main/src/common.rs#L167
[2] https://doc.rust-lang.org/cargo/reference/environment-variables.html

**Comment by messense** [comment]
Fixed in https://github.com/messense/cargo-options/commit/e620e56d724600bf469b3304d1505858303a2e43.
